version: '3'

services:
  onomy:
    image: onomy/testnet-node:local
    restart: on-failure
    container_name: onomy-testnet-node-runner
    environment:
      ETH_RPC_ADDRESS: https://eth-rinkeby.alchemyapi.io/v2/...
    volumes:
      - ./testnet:/root/testnet
    ports:
      # onomy
      - 26656:26656
      - 26657:26657
      - 26660:26660 # prometheus
      - 1317:1317 # swagger
      - 61278:61278
      - 9090:9090
      - 8000:8000 # fauset